### PR TITLE
Release 1.0.0 Using Bootstrap Newsweek Clone Project

### PR DESCRIPTION
**Pull request by pipe2442**
- Created a project basis using Bootstrap 4.5.0.
- Created sections and images with correct spacing using the Bootstrap grid system.
- Fixed margins and padding to give correct responsiveness to the project.
- Developed responsive design and implemented linters configuration and correct HTML validation.
- Fixed README.md file.

### CODE REVIEW

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle:  :traffic_light: 

Hi @pipe2442, great job with this project :+1: README looks professional, PR is descriptive and the project looks great. Going forward we can improve on our commit messages by committing ```fix``` instead of ```fixed```, ```add``` instead of ```added```. Let us get our project approved by fixing the comments below:
- Image is broken, it can not display
img-fix
- Validator errors, let us fix them
val
- ``` Responsiveness ```, the following images will show us how our project looks in terms of responsiveness as compared to the source
``` clone ```
newl
``` source ```
newl1
``` clone ```
mtxt
``` source ```
mtxt1
``` clone ```
medsub
``` source ```
medsub1
``` clone ```, let us align our content as in the source
medsport
``` source ```
medsport1
``` clone ```, 2 columns instead of 4
mededi
``` source ```
mededi1
``` clone ```, let us fix the height and alignment
meditm
```source ```
meditm1
```  clone ```, not responsive
medmt
``` source ```
medmt1
``` clone ```
medcul
``` source ```
medcul1

I am quite sure, you get the picture, I do not want to fill the PR with screenshots. But if you follow the procedure of comparing our clone to the source, I am sure you will fix it. Kindly send me a message if you need some clarification

Kindly implement these changes and submit another code review :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by pipe2442** [comment]
- Fix broken image.
- Fix HTML validation errors.
- Fix Responsiveness issues. 

Thanks for your review @addod19 changes were made!

**Review by BrittanyBlake — CHANGES_REQUESTED** [review]
### Status: Changes Required ♻️ 
****
### Hi @pipe2442!👋 
You have done a great job implementing the changes requested by the previous TSE! 👍 You have also done a wonderful job with your project so far! Your project is really impressive and you have done a great job using bootstrap classes where possible.👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****
The previous TSE requested you compare your clone to the source and make changes. You have done a good job of this so far. Please see below where I have highlighted some areas that could be further improved. 

 **In the Magazine section**

- Large screen:

- [ ] The images in this section are missing the article image tags. Please see my screenshots below.
The original page 👇 
Screen Shot 2020-06-23 at 10 27 00 PM
Your clone 👇 
Screen Shot 2020-06-23 at 10 27 29 PM



 **Editor's Picks section**

- Large screen:
- [ ] The images in this section are also missing the article image tags. (Please ensure that the tags are present on all of the images including, but not limited to, featured stories,top story, culture & travel etc.)
The original page 👇 
Screen Shot 2020-06-23 at 10 28 35 PM
Your clone 👇 
Screen Shot 2020-06-23 at 10 29 06 PM

 **The Debate section**

- Medium screen:

- [ ] The images and text in this sectioned are not properly aligned. There should be more space between them. 
Your clone 👇 
Screen Shot 2020-06-23 at 10 40 24 PM
The original page 👇 
Screen Shot 2020-06-23 at 10 40 59 PM



 **Subscribe section**

- Small screen:

- [ ] The images should overlap a bit more than they do on your clone. Additionally, the text should be centered, yours appears to be left-aligned. Please see my screenshots below. 
Your clone 👇 
Screen Shot 2020-06-23 at 10 37 28 PM

The original page 👇 
Screen Shot 2020-06-23 at 10 38 29 PM


 **Footer**

- Medium and small screen:

- [ ] There should be less of a left margin in both the medium and the small screen. Please see my screenshots below
Your clone 👇 
Screen Shot 2020-06-23 at 10 36 16 PM
The original page 👇 
Screen Shot 2020-06-23 at 10 36 34 PM


****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

**Comment by pipe2442** [comment]
- Add image tags.
- Fix Debate alignment.
- Fix footer margin.
-Fix subscribe image alignment and overlap.

Thanks for the review @BrittanyBlake the changes you requested have been made.

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — APPROVED** [review]
## Status: Approved :trophy:  :balloon: 

Hi @pipe2442, congratulations on a great and beautiful project :+1: You did an awesome job fixing all the comments by previous TSE's :100: 

Go ahead and merge to master, do not forget to submit the project completion form :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by pipe2442** [comment]
Thanks @addod19 !!!!

**Pull request merged**
